### ISSUE TITLE
Prop on ground after diconnect

### ISSUE THREAD

**Issue by GeerdoDaGr8** [VIRUXE/fivem-weaponholster#1]
When logging out or crashing with the gun on you the prop is just placed on the ground.   When logging back in the item will go back to the persons body but if they do not get back on the prop is just on the ground
![image](https://user-images.githubusercontent.com/56656726/153993460-71da4206-2a1e-4142-bab6-4fcb24ddb2e3.png)

**Comment by VIRUXE** [comment]
Thank you. I will account for this in the next version.

**Comment by VIRUXE** [comment]
This is probably fixed with the latest pull request but still needs testing. In theory it should work.

**Comment by JohnnyS** [comment]
This issue is not resolved it still does the same thing it drops on the floor and the object does not delete

**Comment by VIRUXE** [comment]
@JohnnyS are you sure you using the latest version with the code commited by @Senlar ?

Anyway, I'm not using this Inventory anymore so I'm arquiving this repo.
